### ISSUE TITLE
Allow graceful shutdown -- finish current games, don't accept new ones, exit when no games left to play

### ISSUE THREAD

**Issue by arvyy** [lichess-bot-devs/lichess-bot#1010]
**Is your feature request related to a problem? Please describe.**

I want to go to sleep and turn off computer, but I don't want to abandon live games. Sometimes when the last game is finished, a new one is started by another bot creating a challenge

**Describe the solution you'd like**

When configured through options, control-c would cause the bot to finish active games, without starting any new ones, and exit when all games are completed.

**Describe alternatives you've considered**

**Additional context**

**Comment by MarkZH** [comment]
Add this line to your config.yml file with no indentation:
```yaml
quit_after_all_games_finish: true # If set to true, then pressing Ctrl-C to quit will only stop lichess-bot after all current games have finished.
```
More details in the [wiki](https://github.com/lichess-bot-devs/lichess-bot/wiki/Configure-lichess-bot#other-options)

**Comment by arvyy** [comment]
very sorry, not sure how I missed it

**Comment by MarkZH** [comment]
No problem. It's a long wiki page.
