### ISSUE TITLE
Enable Running engines which are runnable jar files

### ISSUE THREAD

**Issue by erberj** [lichess-bot-devs/lichess-bot#1022]
My engine is written in Scala and has no binary (exe) but a runnable jar file

Instead of dir and name of the engine, I suggest to have a run-command variable, where i can enter something like: 
run-command = "java -jar myengine.jar [parameters]"

Best Regards
Jakob Erber

**Comment by MarkZH** [comment]
This is probably a good idea. We'll have to think about how to implement it. In the meantime, you can create an executable with a batch script.

Make a text file with the command to run your engine:
```
java -jar myengine.jar [parameters]
```
Save it to the `lichess-bot/engines/` folder as `myengine.bat` if on Windows or `myengine.sh` on Linux/Mac.

If on Linux/Mac, give that batch script execution permission: `chmod +x myengine.sh`.

Finally, in your `config.yml` file, use the name and location of this script.
```yaml
engine:
  dir: engines
  name: myengine.bat # or .sh
```
Everything else in `config.yml` is the same. I picked the `engines/` directory in the lichess-bot folder for convenience.

**Comment by erberj** [comment]
Thx Mark,I did how you suggested, and it works!Best regardsJakob Am 23.09.24 um 02:11 schrieb Mark Harrison
                
            
            
                
                    Von: "Mark Harrison" ***@***.***>Datum: 23. September 2024An: "lichess-bot-devs/lichess-bot" ***@***.***>Cc: "Jakob Erber" ***@***.***>,"Author" ***@***.***>Betreff: Re: [lichess-bot-devs/lichess-bot] Enable Running engines which are runnable jar files (Issue #1022)
                
                
This is probably a good idea. We'll have to think about how to implement it. In the meantime, you can create an executable with a batch script.
Make a text file with the command to run your engine:
java -jar myengine.jar [parameters]

Save it to the lichess-bot/engines/ folder as myengine.bat if on Windows or myengine.sh on Linux/Mac.
If on Linux/Mac, give that batch script execution permission: chmod +x myengine.sh.
Finally, in your config.yml file, use the name and location of this script.
engine:
  dir: engines
  name: myengine.bat # or .sh
Everything else in config.yml is the same. I picked the engines/ directory in the lichess-bot folder for convenience.
