### ISSUE TITLE
xboard: lichess sends unmotivated undo commands

### ISSUE THREAD

**Issue by erberj** [lichess-bot-devs/lichess-bot#1037]
In a game with my engine, the engine receives undo commands, although I (human user) never requested undos.

Lichess should only send undo command on user request.

[recent.log](https://github.com/user-attachments/files/17356122/recent.log)

**Comment by MarkZH** [comment]
Log copied [here](https://gist.github.com/MarkZH/70bbc71c6eecdfc34bf5ac176b329e02).

It looks like your bot tried to make two moves in a row on both occasions where the `undo` command was sent. On [line 763](https://gist.github.com/MarkZH/70bbc71c6eecdfc34bf5ac176b329e02#file-erberj-issue1037-log-L763), your bot made the move `d2d4`, and then tried to make the move `c5d4` on [line 788](https://gist.github.com/MarkZH/70bbc71c6eecdfc34bf5ac176b329e02#file-erberj-issue1037-log-L788) when it wasn't the bot's turn to move. The `undo` command was sent to make sure your bot was looking at the right board when choosing a move.

**Comment by erberj** [comment]
Thx for your help Mark. I‘m looking into this.Jakob Am 14.10.24 um 03:32 schrieb Mark Harrison
                
            
            
                
                    Von: "Mark Harrison" ***@***.***>Datum: 14. Oktober 2024An: "lichess-bot-devs/lichess-bot" ***@***.***>Cc: "Author" ***@***.***>,"Jakob Erber" ***@***.***>Betreff: Re: [lichess-bot-devs/lichess-bot] xboard: lichess sends unmotivated undo commands (Issue #1037)
                
                
Log copied here.
It looks like your bot tried to make two moves in a row on both occasions where the undo command was sent. On line 763, your bot made the move d2d4, and then tried to make the move c5d4 on line 788 when it wasn't the bot's turn to move. The undo command was sent to make sure your bot was looking at the right board when choosing a move.

**Comment by erberj** [comment]
Error in the engine
