### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by github-jimjim** [lichess-bot-devs/lichess-bot#1059]
**Bug Report**

I discovered an issue with my bot when two players start games against it simultaneously. The error occurs even though I’ve already increased the backoff time. I need help to resolve this problem.

**Error Message:**
```plaintext
INFO     move: 1                                                                 lichess_bot.py:834
INFO     Searching for time 10 seconds for game n69SawFK                      engine_wrapper.py:706
[12/22/24 16:24:55] INFO     Backing off play_game(...) for 0.5s (TimeoutError)                          _common.py:105
INFO     +++ https://lichess.org/n69SawFK/black Schnellschach vs grumpyhedgehog  lichess_bot.py:677
         (1309?) (n69SawFK)
INFO     *** https://lichess.org/n69SawFK/black [player] jomfish_bot: Hello. I  conversation.py:100
         hope you are ready to lose against jomfish_bot. Have fun! For more
         infos type !help.
[12/22/24 16:24:56] INFO     *** https://lichess.org/n69SawFK/black [spectator] jomfish_bot: Hi!    conversation.py:100
         I'm jomfish_bot. Type !help for a list of commands I can respond to.
```
Description: The issue occurs when two players start games against the bot at the same time. The bot seems unable to handle both games concurrently. I tried increasing the backoff time, but the problem persists.

Steps to Reproduce:

Start the bot.
Have two players start games against the bot simultaneously.
The error is triggered.
Suspected Cause: I think there might be an issue with concurrency or a shared resource when play_game(...) attempts to handle two games at the same time.
Propably it is my fault and this isn't a bug but I would still prefer some help.

Questions:

Is there a way to safely parallelize the games?
Should I use a thread pool or an asynchronous queue to manage this?
Thanks for your support!

**Comment by MarkZH** [comment]
Post the logs from the `lichess_bot_auto_logs` directory that show this error. If it exists, post the `config.log` from the same directory, as well. The lines you posted don't show enough information to diagnose the problem.

**Comment by github-jimjim** [comment]
[config.log](https://github.com/user-attachments/files/18228428/config.log)
[lichess-bot.log](https://github.com/user-attachments/files/18228429/lichess-bot.log)

**Comment by MarkZH** [comment]
Thanks for the logs. I've reviewed the logs and I haven't found the issue yet. One thing I have found is that, when the error occurs (PIDs 2768, 11740, 16140, 7472), the engine configuration time (between `ucinewgame; isready` and your engine's response of `readyok`) was more than ten seconds. Once the first move command is sent `go movetime 10000`, the `TimeoutError` occurs 20 seconds after the last `isready`. The two times when there's no error (PIDs 5900 and 7076), configuration takes 0 seconds and 4 seconds, respectively. Normally, the `TimeoutError` would occur 20 seconds after the `go movetime` command. Perhaps a previous `TimeoutError` is somehow held over from the configuration phase?

I need to investigate more and possibly contact the python-chess developer. In the meantime, can you look at your engine and see if you can keep configuration under 10 seconds? If you can, let us know if the error still occurs.

**Comment by github-jimjim** [comment]
Thank you for your help! After testing on another device where everything worked as expected, it seems that the issue was hardware-related. I appreciate the kind support.
