### ISSUE TITLE
Unable to handle response from lichess.org

### ISSUE THREAD

**Issue by yvanlok** [lichess-bot-devs/lichess-bot#655]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/79589802/216401023-4270fb2d-56fe-42d4-9b90-79f0fca9004f.png">

After pulling from the repo, I now get this error

**Comment by AttackingOrDefending** [comment]
You were probably rate limited. Can you send more of the logs, so we can further look into it? You can use `python lichess-bot.py -v -l log.txt` to capture the logs in a text file.

**Comment by MarkZH** [comment]
If you are still having this issue and can provide more details and more logging information, please reopen.
