### ISSUE TITLE
Offering draw based on time

### ISSUE THREAD

**Issue by TheYoBots** [lichess-bot-devs/lichess-bot#668]
Imagine it's a fast game say `1/2+0` and Bot A has 15 seconds on the clock and Bot B has only 2 seconds. Maybe in such cases the Bot A could win the game instead of a draw.

These 2 conditions could be checked before offering a draw:
1. Time difference option: don't offer draw is time difference is less than x seconds.
2. Opponent time: don't offer draw if opponent has less that x seconds in the clock left.

**Comment by MarkZH** [comment]
For time difference, shouldn't the condition be don't offer draw if the time difference is *more* than x seconds? If one player has a lot more time than their opponent, they won't want to offer a draw in hopes of winning on time.

Part of the difficulty here is that the settings for shorter games don't make sense for longer games. In a thirty minute game, a draw offer should still be allowed if one player has 60 more seconds on their clock than their opponent.

**Comment by MarkZH** [comment]
Defining these times in terms of percentages of clock time makes more sense, but I doubt the correct percentage is constant across all game clocks.

Plus, increment time makes this feature even less well-defined. In a `1/2+5` game, both players (bots, especially) will always have plenty of time to move, so draw offers should be allowed.

**Comment by MarkZH** [comment]
This is an interesting idea, but I can't think of how to implement it so that it would be useful for all time controls. If you or anyone comes up with ideas, feel free to reopen this issue.
