### ISSUE TITLE
specify first move in config

### ISSUE THREAD

**Issue by 9glenda** [lichess-bot-devs/lichess-bot#671]
A config option to specify the first move the bot will make. This would make a `e4 bot` or `d4 bot` possible.

**Comment by mheinzel** [comment]
You can achieve this by providing an opening book (see `polyglot` config entry in the README). This also has the advantage that there can be multiple follow-up lines to choose from randomly, so the bot doesn't always react the same way.

**Comment by mheinzel** [comment]
It seems like you can use both, at least the documentation says "This can be a supplement or a replacement for chess databases stored on your computer". So you could make a very minimal opening book only containing a single move (e.g. d4) and after that it would consult chessdb.
