### ISSUE TITLE
Python on Windows

### ISSUE THREAD

**Issue by EmptikBest** [lichess-bot-devs/lichess-bot#709]
When I try to run `python -m pip install --upgrade pip`, I get `Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`.

I've tried all the instructions mentioned in the README.MD file, including installing Python to PATH...
I also installed Python 3.11 from the Microsoft Store as mentioned above, but it still shows the same thing.

**Comment by MarkZH** [comment]
Maybe this will work, especially step 3 (copied from [this StackOverflow answer](https://stackoverflow.com/a/66409838/2156537)):

> 1. Check your Python version and be sure it is installed on your machine
> 2. Check the path environment variable
> 3. Go to -> "start" and type "Manage App Execution Aliases". Go to it and turn off "Python"

The relevant setting may be called "App Installer python.exe" or "App Installer python3.exe".

![python-app-installer](https://user-images.githubusercontent.com/10629050/236668177-fb53bc27-6daa-4295-834d-a3d1ac9c38e9.png)

**Comment by EmptikBest** [comment]
Thank you
