### ISSUE TITLE
Block specific time control for bots

### ISSUE THREAD

**Issue by EmptikBest** [lichess-bot-devs/lichess-bot#716]
Wanted to know if there is any way to block specific time controls for specific bots.
I know you can block some bots entirely but I only want to block challenging those bots with specific time controls.

**Comment by MarkZH** [comment]
That kind of control has not been implemented. Why do you want to do this kind of blocking?

**Comment by EmptikBest** [comment]
I want to do this since I see messages like
 `BOT ResoluteBot (2887) declined Bullet rated challenge from BOT         matchmaking.py:298
                             EmptikBot (2815) (1E0JGzF1): I'm not accepting challenges with this
                             time control.`

**Comment by MarkZH** [comment]
In your config file, put this in the `matchmaking:` section: `challenge_filter: fine`

After a bot declines your challenge, your bot won't issue another challenge for the same type of game to that opponent, including time control.

**Comment by EmptikBest** [comment]
My first question is, will that only apply for the time I keep the application running continously, or if I close it and open it, it will still block.

My second question is, what if that bot accepts 3+2 but not 5+0 in the same variant, does that mean it will also not challenge it for 3+2?

Any help would be appreciated

**Comment by MarkZH** [comment]
1. The block list will be cleared if lichess-bot is restarted.
2. The blocks are based on the names of the time controls: Blitz, Bullet, Rapid, etc. In your scenario, since both 3+2 and 5+0 are blitz games, lichess-bot would not challenge that opponent to either 3+2 or 5+0 after the opponent declined a 5+0.

**Comment by EmptikBest** [comment]
Ok, but it'll still challenge the same bot to 1+0 in the same varient right?

**Comment by AttackingOrDefending** [comment]
Yes. 1+0 is bullet so the bot will still be challenged.

**Comment by EmptikBest** [comment]
Ok, thanks.
