### ISSUE TITLE
Nooby question - specifically, what changes are needed in enginewrapper.py to get an homemade engine connected?

### ISSUE THREAD

**Issue by vibranium21** [lichess-bot-devs/lichess-bot#730]

**Comment by vibranium21** [comment]
Also, I seem to be having import could not be resolved issues?

**Comment by AttackingOrDefending** [comment]
You shouldn't change anything in `engine_wrapper.py`. You should only change `strategies.py`. Can you send your custom code that you have in `strategies.py` or `engine_wrapper.py`?

**Comment by vibranium21** [comment]
Wow, I thought you were supposed to edit in enginewrapper. What should I change in strategies.py?

**Comment by AttackingOrDefending** [comment]
You should change the `search` function. There are many example engines like `RandomMove`. Change `engine_wrapper.py` to the default one and add your code to `strategies.py`. Then if you still have the problem send your code in `strategies.py`, so I can see what causes the error. Also, can you run lichess-bot with `python lichess-bot.py -v -l log.txt` and upload the log?

**Comment by vibranium21** [comment]
How would I get the player color in my code?

**Comment by AttackingOrDefending** [comment]
Yes, just change `player_color = board.side_to_move` to `player_color = board.turn` and put the code inside a class.

**Comment by vibranium21** [comment]
[06/09/23 13:37:33] INFO     Backing off play_game(...) for 0.4s (OSError: [WinError 193] %1 is not a     _common.py:105
                             valid Win32 application)
                    INFO     Backing off play_game(...) for 0.7s (OSError: [WinError 193] %1 is not a     _common.py:105
                             valid Win32 application)
[06/09/23 13:37:35] INFO     Backing off play_game(...) for 3.5s (OSError: [WinError 193] %1 is not a     _common.py:105
                             valid Win32 application)
[06/09/23 13:37:38] INFO     Backing off play_game(...) for 7.9s (OSError: [WinError 193] %1 is not a     _common.py:105
                             valid Win32 application)
[06/09/23 13:37:47] INFO     Backing off play_game(...) for 3.5s (OSError: [WinError 193] %1 is not a     _common.py:105
                             valid Win32 application)
[06/09/23 13:37:51] INFO     Backing off play_game(...) for 7.8s (OSError: [WinError 193] %1 is not a     _common.py:105
                             valid Win32 application)
[06/09/23 13:37:59] INFO     Backing off play_game(...) for 55.7s (OSError: [WinError 193] %1 is not a    _common.py:105
                             valid Win32 application)

**Comment by vibranium21** [comment]
Have you seen this problem before?

**Comment by AttackingOrDefending** [comment]
Have you put `protocol: "homemade"` and `name: "YOUR CLASS NAME"` in config.yml? Can you send your logs from the start of lichess-bot when run with `-v`?

**Comment by vibranium21** [comment]
I did not have name as class name, that could possibly be the issue. But the engine uses uci.

**Comment by AttackingOrDefending** [comment]
If your engine isn't an executable and is connected to lichess-bot through `strategies.py` then the protocol is "homemade".

**Comment by vibranium21** [comment]
I switched it to homemade but I am still getting the  INFO     Backing off play_game(...) for 88.7s (OSError: [WinError 193] %1 is not a    _common.py:105
                             valid Win32 application) error

**Comment by vibranium21** [comment]
[log.txt](https://github.com/lichess-bot-devs/lichess-bot/files/11708980/log.txt)

**Comment by vibranium21** [comment]
What about the engines directory?

**Comment by AttackingOrDefending** [comment]
Nothing will happen if you change it, so there is no reason to.

**Comment by vibranium21** [comment]
Can I remove the ExampleEngine inheritance? I am getting errors  INFO     Backing off play_game(...) for 73.7s (NameError: name 'ExampleEngine' is not _common.py:105
                             defined)

**Comment by AttackingOrDefending** [comment]
https://github.com/AttackingOrDefending/lichess-bot/tree/vibranium
I fixed all the errors. Download it, rename `config.yml.default` to `config.yml`, add your token and it should be working.

**Comment by vibranium21** [comment]
tysm for doing this and putting up with my lack of lichess-bot experience
