### ISSUE TITLE
confused.

### ISSUE THREAD

**Issue by ethicalhacker7192** [lichess-bot-devs/lichess-bot#737]
I am confused, I want to make a engine entirely in python but every time I try it keeps saying the error:

    [06/13/23 11:19:03] INFO     Backing off play_game(...) for 124.6s (AttributeError: module 'strategies'   _common.py:105
                             has no attribute 'engine.py')

**Comment by ethicalhacker7192** [comment]
do I have to compile? because I like not compiling code for easy modification and debugging.

**Comment by MarkZH** [comment]
No compiling is necessary. You do need to create a class in strategies.py that has a `search()` method that calls your code for finding a move given a board position. Look at the other examples in strategies.py to see how they work. In your configuration file, the name of the engine should be a class name in strategies.py. Add the line `import engine` to strategies.py to use the code you've written.

**Comment by ethicalhacker7192** [comment]
also how do I compile a python based engine to the needed one (is it .exe or what is it?)

**Comment by ethicalhacker7192** [comment]
nvm, accidentally read wrong, however, I still need to see examples of the strategies.py and engines people have made.

**Comment by AttackingOrDefending** [comment]
In [strategies.py](https://github.com/lichess-bot-devs/lichess-bot/blob/master/strategies.py) there are some example engines (`RandomMove`, `Alphabetical`, and `FirstMove`). Your engine should have the structure:
```python
class MyEngine(ExampleEngine):
    def search(self, board: chess.Board, *args: Any) -> PlayResult:
        MY CODE HERE
        return PlayResult(engines_move, None)
```

**Comment by ethicalhacker7192** [comment]
Thanks for the help! I got my first chess agent going! It is a self learning AI model.
