### ISSUE TITLE
RuntimeErorr

### ISSUE THREAD

**Issue by M-DinhHoangViet** [lichess-bot-devs/lichess-bot#740]
[06/15/23 14:52:55] ERROR    Quitting lichess-bot due to an error:                                   lichess-bot.py:994
                             Traceback (most recent call last):
                               File "C:\Downloads\lichess-bot-master
                             (1)\lichess-bot-master\lichess-bot.py", line 991, in <module>
                                 start_lichess_bot()
                               File "C:\Downloads\lichess-bot-master
                             (1)\lichess-bot-master\lichess-bot.py", line 937, in start_lichess_bot
                                 li = lichess.Lichess(CONFIG.token, CONFIG.url, __version__,
                             logging_level, max_retries)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^
                               File "C:\Downloads\lichess-bot-master
                             (1)\lichess-bot-master\lichess.py", line 95, in __init__
                                 raise RuntimeError("Please use an API access token for your bot
                             that "
                             RuntimeError: Please use an API access token for your bot that has the
                             scope "Play games with the bot API (bot:play)". The current token has:
                             ['email:read', ' preference:read', ' preference:write', ' follow:read',
                             ' follow:write', ' msg:write', ' challenge:read', ' challenge:write', '
                             challenge:bulk', ' tournament:write', ' team:read', ' team:write', '
                             team:lead', ' puzzle:read', ' racer:write', ' study:read', '
                             study:write', ' bot:play', ' engine:read', ' engine:write'].

**Comment by vibranium21** [comment]
O glad I found this. Was having this problem as well

**Comment by M-DinhHoangViet** [comment]
Ok, thank
