### ISSUE TITLE
Not recognizing Bot:play

### ISSUE THREAD

**Issue by Oqarshi** [lichess-bot-devs/lichess-bot#742]
gives this error when trying to execute "python lichess-bot.py –u" even though the api token has bot:play                             
                             
                             RuntimeError: Please use an API access token for your bot that has the
                             scope "Play games with the bot API (bot:play)". The current token has:
                             ['email:read', ' preference:read', ' preference:write', ' follow:read',
                             ' follow:write', ' msg:write', ' challenge:write', ' challenge:bulk', '
                             tournament:write', ' team:read', ' team:write', ' team:lead', '
                             puzzle:read', ' racer:write', ' study:read', ' study:write', '
                             bot:play', ' engine:read', ' engine:write'].

**Comment by AttackingOrDefending** [comment]
Download the latest lichess-bot version and it should work.

**Comment by Oqarshi** [comment]
works thanks

**Comment by Oqarshi** [comment]
works thanks
