### ISSUE TITLE
Engine error when more or equal than 2048 mb of ram engine crashes

### ISSUE THREAD

**Issue by Oqarshi** [lichess-bot-devs/lichess-bot#746]
**Describe the bug**
When allocating more than 2048 mb of ram to engine, example if i allocate 2048 mb ram an error occurs and the engine doesent play. I am not running out of ram as i still have an extra 8 gb of ram

**To Reproduce**
1. Allocat equal to or more than 2048 mb of ram
2. Run lichess-bot like normal
3. See error

**Expected behavior**
The engine plays normally

**Logs**
![image](https://github.com/lichess-bot-devs/lichess-bot/assets/94034118/1b520582-1780-45ea-abc2-9b85e1e264bb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version: 3.11.4

**Additional context**
The book moves play normally the engine is only affected so book moves from book.bin play normally only after when all book moves are finished the engine crashes. Does not crash when allocating less than 2048 mb of ram

**Comment by AttackingOrDefending** [comment]
My first thought is that the engine you are using is 32 bits. Can you download the latest version of lichess-bot and when you close it, upload the logs from the `lichess_bot_auto_logs` folder?

**Comment by Oqarshi** [comment]
should i upload the entire thing?

**Comment by Oqarshi** [comment]
[recent.log](https://github.com/lichess-bot-devs/lichess-bot/files/11792778/recent.log)

**Comment by MarkZH** [comment]
I see two errors in the logs. The first is easy.
```
2023-06-19 13:02:47,777 __mp_main__ (lichess-bot.py:567) DEBUG Initial state: {'error': 'This game cannot be played with the Bot API.'}
2023-06-19 13:02:47,777 backoff (_common.py:105) INFO Backing off play_game(...) for 0.1s (KeyError: 'id')
```
Lichess does not allow bots to play ultrabullet games.

The second error (and the one that's relevant to this issue) seems to happen right after the configuration parameters are sent to stockfish.
```
2023-06-19 13:03:04,887 chess.engine (engine.py:1049) DEBUG <UciProtocol (pid=8320)>: >> uciok
2023-06-19 13:03:04,887 chess.engine (engine.py:1023) DEBUG <UciProtocol (pid=8320)>: << setoption name Move Overhead value 100
2023-06-19 13:03:04,888 chess.engine (engine.py:1023) DEBUG <UciProtocol (pid=8320)>: << setoption name Threads value 2
2023-06-19 13:03:04,888 chess.engine (engine.py:1023) DEBUG <UciProtocol (pid=8320)>: << setoption name Hash value 2048
2023-06-19 13:03:04,888 chess.engine (engine.py:1023) DEBUG <UciProtocol (pid=8320)>: << setoption name SyzygyPath value ./syzygy/
2023-06-19 13:03:04,888 __mp_main__ (lichess-bot.py:573) DEBUG The engine for game pJRDYo7o has pid=8320
2023-06-19 13:03:04,888 __mp_main__ (lichess-bot.py:576) INFO +++ https://lichess.org/pJRDYo7o/black Bullet vs AI level 8 (pJRDYo7o)
2023-06-19 13:03:04,889 conversation (conversation.py:84) INFO *** https://lichess.org/pJRDYo7o/black [player] Chessler-V3: Hi! I'm Chessler-V3. Good luck! Type !help for a list of commands I can respond to.
2023-06-19 13:03:04,906 chess.engine (engine.py:1020) DEBUG <UciProtocol (pid=8320)>: Process exited
2023-06-19 13:03:04,906 chess.engine (engine.py:1007) DEBUG <UciProtocol (pid=8320)>: Connection lost (exit code: 1, error: None)
```
The engine process dies right after the `setoption` lines and the lichess-bot errors occurs when the dead engine is asked for a move.

I see that you are using Stockfish 10. Does this happen on later versions of Stockfish? The current version is 15.

Try the following script with your engine and let us know if the problem still occurs. The script plays a game with your engine with your config settings. If the engine dies with the script, maybe a better error message will be printed. In any case, post the debugging messages here.
```python
import chess
import chess.engine
import logging

logging.basicConfig(level=logging.DEBUG)

engine = chess.engine.SimpleEngine.popen_uci("./path/to/your/engine")
engine.configure({
    "Move Overhead": 100,
    "Threads": 2,
    "Hash": 2048,
    "SyzygyPath": ./syzygy/})

board = chess.Board()
while not board.is_game_over():
    result = engine.play(board, chess.engine.Limit(time=0.1))
    board.push(result.move)

engine.quit()
```

**Comment by Oqarshi** [comment]
I run the code with the example engine and i get this debug/error message:

DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:chess.engine:<UciProtocol (pid=10328)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << uci
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> Stockfish 10 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> id name Stockfish 10
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> 
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Debug Log File type string default 
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Contempt type spin default 24 min -100 max 100
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Analysis Contempt type combo default Both var Off var White var Black var Both
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Threads type spin default 1 min 1 max 512
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Hash type spin default 16 min 1 max 2048
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Clear Hash type button
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Ponder type check default false
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name MultiPV type spin default 1 min 1 max 500
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Skill Level type spin default 20 min 0 max 20
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Move Overhead type spin default 30 min 0 max 5000
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Minimum Thinking Time type spin default 20 min 0 max 5000
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Slow Mover type spin default 84 min 10 max 1000
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name nodestime type spin default 0 min 0 max 10000
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name UCI_Chess960 type check default false
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name UCI_AnalyseMode type check default false
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name SyzygyPath type string default <empty>
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name SyzygyProbeDepth type spin default 1 min 1 max 100
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name Syzygy50MoveRule type check default true
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> option name SyzygyProbeLimit type spin default 7 min 0 max 7
DEBUG:chess.engine:<UciProtocol (pid=10328)>: >> uciok
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << setoption name Move Overhead value 100
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << setoption name Threads value 2
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << setoption name Hash value 2048
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << setoption name SyzygyPath value ./syzygy/
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << ucinewgame
DEBUG:chess.engine:<UciProtocol (pid=10328)>: << isready
WARNING:chess.engine:<UciProtocol (pid=10328)>: stderr >> Failed to allocate 2048MB for transposition table.
DEBUG:chess.engine:<UciProtocol (pid=10328)>: Process exited
DEBUG:chess.engine:<UciProtocol (pid=10328)>: Connection lost (exit code: 1, error: None)
Traceback (most recent call last):
  File "c:\Users\deena\import chess.py", line 16, in <module>
    result = engine.play(board, chess.engine.Limit(time=0.1))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deena\AppData\Local\Programs\Python\Python311\Lib\site-packages\chess\engine.py", line 2795, in play
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\deena\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deena\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\deena\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\deena\AppData\Local\Programs\Python\Python311\Lib\site-packages\chess\engine.py", line 1685, in play
    return await self.communicate(UciPlayCommand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deena\AppData\Local\Programs\Python\Python311\Lib\site-packages\chess\engine.py", line 1094, in communicate
    return await command.result
           ^^^^^^^^^^^^^^^^^^^^
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)
PS C:\Users\deena>

**Comment by Oqarshi** [comment]
For some reason when i try it with later versions of stockfish 14 and up it has not problem allocating the ram. It must be some issue with the older versions. Thanks for the help with this error!
