### ISSUE TITLE
How to add NNUE to chess engine

### ISSUE THREAD

**Issue by Oqarshi** [lichess-bot-devs/lichess-bot#753]
where do you set a path to you NNUE file in config.yml? is there even an option?

![image](https://github.com/lichess-bot-devs/lichess-bot/assets/94034118/1a849358-3eea-471e-8b28-c0a73f5b4f30)

**Comment by MarkZH** [comment]
Under `uci_options` put `EvalFile: <file name>`

The NNUE file needs to be put in the same directory as the stockfish executable file.

See the "Trying it out" section here: https://stockfishchess.org/blog/2020/introducing-nnue-evaluation/
