### ISSUE TITLE
% Hash is very low even in long games

### ISSUE THREAD

**Issue by TheYoBots** [lichess-bot-devs/lichess-bot#771]
For some reason even in long rapid games, my Bot doesn't exceed `hashfull 150` (15% Hash) Is there any way to set a minimum value for this so that a move isn't made unless it reaches that value?

**Comment by AttackingOrDefending** [comment]
There is no way to set a minimum hash value. You are probably using a high hash value. How much is your hash? If you are hosting your bot on heroku, after 1 minute of search stockfish will probably have used around 70MB of hash.
