### ISSUE TITLE
Create and maintain official `lichess-bot` Docker image

### ISSUE THREAD

**Issue by eduherminio** [lichess-bot-devs/lichess-bot#780]
## Problem

I would like to use `lichess-bot` with a custom engine in Windows, Mac and Linux, either AMD or ARM, without having to worry about installing/updating its (python) dependencies.

## Proposed solution

A potential solution to that is to create a Docker image that has all `lichess-bot` dependencies pre-installed.

Ideally I envision that Docker image having this repository checked out there (that is, generating a new image per `lichess-bot` release).

Then it would be a matter of attaching a volume(s) to the container in order to share the engine binaries with it and customize the `config.yml` file to point at it, use the right token and configure the desired bot behavior.

Ideally we would like to achieve an implementation (+ sample scripts/commands) that doesn't require us to enter the Docker container for anything.

I'd be more than happy to get involved into the implementation and maintenance of this solution.

## PoCs

This week I kinda already implemented something like this in [lichess-bot-playground](https://github.com/lynx-chess/lichess-bot-playground), but not in an optimal way (the image, while functional, should be as small as possible and I generated it on top of the not exactly slim `python` image). It also requires entering the container to manually modify the `config.yml` file, so this is still far from a perfect solution.

Back in the day I also implemented something similar in [Lynx_BOT](https://github.com/lynx-chess/Lynx_BOT), but embedding the engine itself in the image.
This is a more advanced solution in terms of not having to manually enter the container, since the problem of providing the desired configuration is solved there with a `docker-compose` file that copies the desired `config.yml` file into the container.

## Summary

My idea would be to create a `lichess-bot` image and provide either a sample docker command (similar to the one in the README of [lichess-bot-playground](https://github.com/lynx-chess/lichess-bot-playground) or a sample docker compose file (see [`docker-compose.yml` file in Lynx_BOT](https://github.com/lynx-chess/Lynx_BOT/blob/main/docker-compose.yml)) that achieve that second purpose of being able to provide the engine binaries and the configuration files without having to manually enter the container generated from the docker image.

This image could be use as a base image for engine images, in a similar fashion as I did with Lynx_BOT: adding the engine binaries on top of it. Note that the custom `config.yml` could also be added to engine images, but since that configuration is more likely to be tweaked often, I'd still recommend to inject it separately and keep engine image versions as wrappers of the equivalent (same number) engine versions that have a certain `lichess-bot` version side to side with it, setup and ready to be used to connect that engine to lichess.

**Comment by AttackingOrDefending** [comment]
Installing lichess-bot in linux/macos requires a package manager ([see here](https://github.com/lichess-bot-devs/lichess-bot/wiki/How-to-Install#maclinux)). Do you know how we can create a docker that supports multiple linux versions? I haven't used docker before, so I'm not sure how it is done.

**Comment by eduherminio** [comment]
A docker image is self-contained by definition, once it's built it can be run in Windows/any linux flavour/macos.
Docker images are built in layers (one image on top of another), for instance [python image](https://hub.docker.com/_/python) has versions built on top of debian and alpine.

And running them creates locally what's called a container, which is effectively like running an isolated mini-instance of those OSes with whatever you put inside when you built the image. You can actually go inside and run any command or install anything you want on top of what you have, but that won't be persisted next time you run create a different container from that image.

During the process of building our image is when those dependencies need to be installed (see https://github.com/lynx-chess/lichess-bot-playground/blob/main/Dockerfile#L9-L11 as an example, which I built on top of the python image which was built on top of debian). And depending on the base image you chose, the process of doing that is one or another.

But all that is solved by the image creator/maintainer, not by the image user, which just needs to worry about sharing with the local container created from that image the right engine and configuration.

Right now if you run `docker run ghcr.io/lynx-chess/lichess-bot-playground:1.0.0-alpha.2 python3 lichess-bot.py` you'll execute `python3 lichess-bot.py` command inside of a debian image with python installed, with lichess-bot repo cloned and with lichess-bot dependencies installed. And you just need to have docker installed for that.

You would get the same behavior no matter where you run it from (OS, machine, etc.), which in this case is an error because of the lack of chess engine in the default engine path:
```bash
 docker run ghcr.io/lynx-chess/lichess-bot-playground:1.0.0-alpha.2 python3 lichess-bot.py
[07/14/23 11:49:45] INFO                                      lichess-bot.py:965
                                 .   _/|
                                 .  // o\
                                 .  || ._)  lichess-bot
                             2023.7.11.3
                                 .  //__\
                                 .  )___(   Play on Lichess
                             with a bot

[07/14/23 11:49:46] ERROR    Quitting lichess-bot due to an  lichess-bot.py:1027
                             error:
                             Traceback (most recent call
                             last):
                               File
                             "/home/src/lichess-bot/lichess-
                             bot.py", line 1024, in <module>
                                 start_lichess_bot()
                               File
                             "/home/src/lichess-bot/lichess-
                             bot.py", line 966, in
                             start_lichess_bot
                                 CONFIG =
                             load_config(args.config or
                             "./config.yml")
                               File
                             "/home/src/lichess-bot/config.p
                             y", line 356, in load_config
                                 validate_config(CONFIG)
                               File
                             "/home/src/lichess-bot/config.p
                             y", line 263, in
                             validate_config
                                 config_assert(os.path.isfil
                             e(engine) or
                             CONFIG["engine"]["protocol"] ==
                             "homemade",
                               File
                             "/home/src/lichess-bot/config.p
                             y", line 75, in config_assert
                                 raise
                             Exception(error_message)
                             Exception: The engine
                             ./engines/engine_name file does
                             not exist.
```
