### ISSUE TITLE
Bot won't play after accepting a challenge

### ISSUE THREAD

**Issue by Eliagiac** [lichess-bot-devs/lichess-bot#784]
I followed the steps listed in the [wiki](https://github.com/lichess-bot-devs/lichess-bot/wiki) to have a bot account on Lichess for my engine, but I haven't yet been able to play against it.

After sending it a challenge, the game starts properly and I can make a move if playing white. Then, nothing happens, and the clocks never start.

Whenever it receives a challenge, the following message is printed:
`Backing off play_game(...) for 0.0s (TimeoutError)`

Here's a detailed [log](https://github.com/lichess-bot-devs/lichess-bot/files/12123558/recent.log) of the errors. I am on Windows 11 with Python 3.11.0.

Any help would be appreciated!

**Comment by MarkZH** [comment]
After your engine prints `id name ...` and `id author ...`, it should print `uciok` to indicate that it is done with sending ID information and options (`option name ... type ...`), if any.

**Comment by MarkZH** [comment]
What's happening is that the python-chess module that we use to run the engines gives up and terminates the engine after 10 seconds of waiting for the `uciok` message.

**Comment by Eliagiac** [comment]
Thank you, my engine is now up and running!

After adding the 'uciok' message, and implementing a few missing mandatory settings such as 'Threads', 'Move Overhead' and 'SyzygyPath', everything worked smoothly.

**Comment by MarkZH** [comment]
> Thank you, my engine is now up and running!
> 
> After adding the 'uciok' message, and implementing a few missing mandatory settings such as 'Threads', 'Move Overhead' and 'SyzygyPath', everything worked smoothly.

Great! One last thing. None of those settings are mandatory. They are examples. Go ahead and delete them from your config file if you don't need them.
