### ISSUE TITLE
When at this eval maybe like +1, It suddenly drops again. Which lead me confused why this engine don't convert their advantage clearly 

### ISSUE THREAD

**Issue by olypnsf** [lichess-bot-devs/lichess-bot#803]
When at this eval maybe like +1, It suddenly drops again. Which lead me confused why this engine don't convert their advantage clearly 

I like to add some function for the engine in config.py if the eval is +1 then the engine is maximized to find the best move in the position

**Comment by AttackingOrDefending** [comment]
Run lichess-bot and when this happens again, close it and then upload the files inside the `lichess_bot_auto_logs` directory. There should be 2 files named `recent.log` and `old.log`.

**Comment by TheYoBots** [comment]
I think he wants the engine to play stronger/better moves when it reaches +-1 eval. But I don't think lichess bot determines this. Unless you want to purposefully weaken the bot until it reaches +-1 Eval?

**Comment by MarkZH** [comment]
An evaluation of +1, which means the engine is about one pawn ahead, is not that great of an advantage. The evaluation is also only an estimate.

Chess engines are limited in how far ahead they can search. During the next move, the engine will be able to search two moves further than the previously (after the engine's move and the opponent's move), which may change the next evaluation due to getting more information.

**Comment by AttackingOrDefending** [comment]
It's possible that the +1 eval is from chessdb (possibly at depth 30+) and when the engine starts to think it doesn't see that far so it reports a lower score. Looking at a [game](https://lichess.org/f1uGQ24g) and at your [repo](https://github.com/olypnsf/Geometrics-Experimental) try disabling `go_commands`, lowering `Move Overhead` in `uci_options`, and slightly increasing `max_depth` in the opening book section. Also, I'm not sure how strong Cerebellum is at the moment. I think that the last version was released about 2 years ago.

**Comment by olypnsf** [comment]
Ok @AttackingOrDefending  If i increase the max depth what is the best values?

**Comment by MarkZH** [comment]
@olypnsf Are there any more questions for this issue?
