### ISSUE TITLE
Contributing to lichess-bot

### ISSUE THREAD

**Issue by AttackingOrDefending** [lichess-bot-devs/lichess-bot#824]
If someone wants to contribute, here are some changes that they can make:

- Add tests for specific functions (e.g. `get_lichess_cloud_move`)
- Add docker (#780)
- Improve mypy typings (replace `Any` with dataclass)

**Comment by M-DinhHoangViet** [comment]
You should write this in PR because before contributing they have to go to https://github.com/lichess-bot-devs/lichess-bot/pulls

**Comment by MarkZH** [comment]
The issues listed here have been separated into #780, #920, and #921.
