### ISSUE TITLE
There are some errors after scanning the encoding with pylint

### ISSUE THREAD

**Issue by M-DinhHoangViet** [lichess-bot-devs/lichess-bot#825]
https://github.com/M-DinhHoangViet/lichess-bot-1/actions/runs/5983346634/job/16233386569

**Comment by TheYoBots** [comment]
This repository already uses `flake8` for linting code: https://github.com/lichess-bot-devs/lichess-bot/blob/b4bd7815220c16ee2d693a3e40783b472f57091e/.github/workflows/python-build.yml#L31-L44

**Comment by M-DinhHoangViet** [comment]
Turns out that's why the error warning was ignored
