### ISSUE TITLE
"301 Moved Permanently" when trying to upgrade to bot

### ISSUE THREAD

**Issue by Jaqb-Janicqi** [lichess-bot-devs/lichess-bot#851]
Hello, I have created a new account and have not touched anything outside of creating an api token.
When i input the api token in "token" field in config.yml (i have created config.yml by copying and renaming default),
I get a console printout "Nie mo", which i assume is "Could not" in english but the output appears to be cut.
When i instead run the following command in windows cmd:
curl -d '' [lichess.org/api/bot/account/upgrade](http://lichess.org/api/bot/account/upgrade) -H "Authorization: Bearer TOKEN"
I get:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

1. run: python3 lichess-bot.py -u
2. output "Nie mo" ("Could not" maybe)
or
1. curl -d '' [lichess.org/api/bot/account/upgrade](http://lichess.org/api/bot/account/upgrade) -H "Authorization: Bearer TOKEN"
2. output: 301 Moved Permanently

**Expected behavior**
{"ok":true}

**Logs**
there are no logs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.10.13

**Additional context**
As I have said, I have created a fresh account.
I dont believe there was ever an account under the email address I used.
Thank You for your work and help in advance :)

Images:
<img width="641" alt="curl_error" src="https://github.com/lichess-bot-devs/lichess-bot/assets/28823374/40d0a615-c121-4664-9bfd-b5de96285ff2">
<img width="455" alt="python3_error" src="https://github.com/lichess-bot-devs/lichess-bot/assets/28823374/57959ed8-7bd0-4366-9b88-7d99b6665ec1">
<img width="437" alt="config_used" src="https://github.com/lichess-bot-devs/lichess-bot/assets/28823374/e2a3a481-2447-43f5-85e9-be3f3b0fe29c">

**Comment by MarkZH** [comment]
Do you have logs available in the `lichess_bot_auto_logs` folder in your lichess-bot directory? Those might have more information. Post the contents of the log files here.

**Comment by Jaqb-Janicqi** [comment]
Hi, there is no such folder in lichess-bot directory.

**Comment by Jaqb-Janicqi** [comment]
Hi, I have managed to solve it by specifying https before lichess domain in curl.
Guess copying commands straight from forums isn't great.
Anyhow I don't see why I wasn't able to upgrade with the "python3 lichess-bot.py -u" method.

**Comment by MarkZH** [comment]
It seems like "Nie mo" is a python error message that gets printed when something in a virtual environment fails. Can you run python by itself on the command line in an interactive session? Are you using the virtual environment when you run lichess-bot?

- https://discuss.python.org/t/problems-with-installing-python-3-7/16203
- https://stackoverflow.com/questions/75705998/unable-to-create-virtual-environment-nie-mo-error
- https://stackoverflow.com/questions/70583853/cant-run-python-program-in-command-prompt

**Comment by Jaqb-Janicqi** [comment]
Hi, sorry for a delayed response. I am using an anaconda environment and have also tried running the upgrade command on base python without any environment. I can start start an interactive session in both cases.

**Comment by MarkZH** [comment]
What happens if you run lichess-bot with these commands?
1. `venv\Scripts\activate`
2. `python3 lichess-bot.py`

**Comment by Jaqb-Janicqi** [comment]
Hi, when I run:
```python3 lichess-bot.py``` or ```python3 lichess-bot.py -u``` i get "Nie mo".
However, if I run:
```python lichess-bot.py``` or ```python lichess-bot.py -u``` i get "Exception: The engine ./engines/engine_name file does not exist.".
Didn't know I needed to have an engine to upgrade the account with the repo. Thanks for Your help and have a great day!
