### ISSUE TITLE
Liches Variants

### ISSUE THREAD

**Issue by partharor** [lichess-bot-devs/lichess-bot#857]
I Make My Bot play variants but in CMD it says, Unexpected engine output: 'info string Found 0 tablebases. Please Help.

**Comment by AttackingOrDefending** [comment]
This shouldn't cause the bot to crash. If you don't have tablebases for any variant you can comment out the line `SyzygyPath: "./syzygy/"` in [`config.yml`](https://github.com/lichess-bot-devs/lichess-bot/blob/master/config.yml.default#L93).

**Comment by MarkZH** [comment]
This might be related to this bug in python-chess: https://github.com/niklasf/python-chess/issues/1049

Try removing `info string` output before a game starts.

**Comment by partharor** [comment]
> This shouldn't cause the bot to crash. If you don't have tablebases for any variant you can comment out the line `SyzygyPath: "./syzygy/"` in [`config.yml`](https://github.com/lichess-bot-devs/lichess-bot/blob/master/config.yml.default#L93).

What Does Comment Out mean?

**Comment by MarkZH** [comment]
Put a hash mark `#` at the beginning of that line. It will cause the line to be ignored by lichess-bot. The line would look like this:
```yaml
# SyzygyPath: "./syzygy/"
```

**Comment by partharor** [comment]
> Put a hash mark `#` at the beginning of that line. It will cause the line to be ignored by lichess-bot. The line would look like this:
> 
> ```yaml
> # SyzygyPath: "./syzygy/"
> ```

I have done it But it now says " Backing off play_game(...) for 3.5s (chess.engine.EngineError: engine does not support UCI_Variant)"

**Comment by AttackingOrDefending** [comment]
Stockfish doesn't support playing variants. You can use [Fairy-Stockfish](https://github.com/fairy-stockfish/Fairy-Stockfish#installation) instead.

**Comment by partharor** [comment]
> Stockfish doesn't support playing variants. You can use [Fairy-Stockfish](https://github.com/fairy-stockfish/Fairy-Stockfish#installation) instead.

Thanks
