### ISSUE TITLE
info message pv parsing promotions

### ISSUE THREAD

**Issue by LyubenGeorgiev** [lichess-bot-devs/lichess-bot#900]
**Describe the bug**
When I output info message including pv that has a promotion moves I get parsing error.

**To Reproduce**
1. Run lichess-bot with my custom bot implementing UCI cli
2. Example output:
info score cp 1086 depth 2 time 0 pv b7b8Q f8f7 d1e2

**Expected behavior**

**Logs**
ERROR    Exception parsing pv from info: 'score cp 1086 depth 2 time 0 pv b7b8Q f8f7 d1e2 ', position at root: 5k2/1P6/5p2/8/8/8/5PP1/3K4 w - - 1 61

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.10.12

**Additional context**
There is no error if the pv does not contain a promotion move.

**Comment by MarkZH** [comment]
Does outputting the promotion piece in lowercase (b7b8q) solve the problem?

**Comment by LyubenGeorgiev** [comment]
Yes it does
