### ISSUE TITLE
Problems creating a leela bot

### ISSUE THREAD

**Issue by thechipsss** [lichess-bot-devs/lichess-bot#914]
![image](https://github.com/lichess-bot-devs/lichess-bot/assets/91486076/17286f78-f9d1-45cb-b515-6d4567415f45)
I am having this issue when i am trying to make a leela bot can anbody herlp me pls

**Comment by thechipsss** [comment]
![image](https://github.com/lichess-bot-devs/lichess-bot/assets/91486076/6a55b03a-183f-44c0-9a61-5f6e49a82235)

**Comment by thechipsss** [comment]
![image](https://github.com/lichess-bot-devs/lichess-bot/assets/91486076/037cce0f-a403-434d-a11d-e85aae3b59ee)
engine folder

**Comment by AttackingOrDefending** [comment]
This problem happens because Leela doesn't support any option named `Move Overhead`. In your `config.yml`, under `uci_options` you can change `Move Overhead` to `MoveOverheadMs` or remove this line completely to fix this issue.

**Comment by thechipsss** [comment]
![image](https://github.com/lichess-bot-devs/lichess-bot/assets/91486076/aed8273d-df9e-42bc-9b2b-6c589a020ae0)
@AttackingOrDefending

**Comment by thechipsss** [comment]
> This problem happens because Leela doesn't support any option named `Move Overhead`. In your `config.yml`, under `uci_options` you can change `Move Overhead` to `MoveOverheadMs` or remove this line completely to fix this issue.

i rempved the line so i have to remove the hash line too?

**Comment by thechipsss** [comment]
Thanks created the bot :)

**Comment by thechipsss** [comment]
how t

**Comment by thechipsss** [comment]
How to reduce the time taken for thinking it takes 10 s to think?

**Comment by AttackingOrDefending** [comment]
If you want to make your bot move faster, try adding `MoveOverheadMs: 1000` under `uci_options`.

**Comment by MarkZH** [comment]
Also, the bot will take 10 seconds to choose the first move of the game. Then, thinking time is determined by the time control of the game.

**Comment by thechipsss** [comment]
Thanks for idea! i will close this now.

**Comment by thechipsss** [comment]
bye
