### ISSUE TITLE
Improving type annotations

### ISSUE THREAD

**Issue by MarkZH** [lichess-bot-devs/lichess-bot#921]
Many places in the code are annotated with `Any` types that could use some more specific type annotations. This is especially true when parsing user's configuration files and JSON messages from lichess.org.

**Comment by greg-finley** [comment]
It will be a very long slog to get there and maybe not worth it?

This was an attempt just to get the user profile endpoint typed, and it's only half done / risky

https://github.com/lichess-bot-devs/lichess-bot/compare/master...greg-finley:lichess-bot:types

**Comment by MarkZH** [comment]
When we first added typing to lichess-bot, it took several pull requests going component-by-component over several months: #620, #640, #647, and #649. This way is actually easier to review. At first glance, what you have looks like a good start. Feel free to open a PR when you get to a good stopping point.
