### ISSUE TITLE
Question: Can one VM run two bots?

### ISSUE THREAD

**Issue by greg-finley** [lichess-bot-devs/lichess-bot#931]
The high-level steps I tried were:
1. Spin up a VM on Google Cloud.
2. Clone the bot repo, set it up, run it.
3. Clone the bot repo again, set it up as another bot with a different API key, run it.
4. The VM just freezes. Cntl-C doesn't work to disconnect from the VM. Both bots stop responding to challenges. Need to just kill the VM and start over.

My two bots are happily running on separate VMs, but would be nice to share one VM for Google Cloud free tier.

This freezing happens whether I run as `systemd` service or run directly.

More detailed setup commands are [here](https://github.com/greg-finley/lichess-bot-min-opponent-moves/blob/main/VMSetup.md). The configs and `systemd` jobs for the bots are [here](https://github.com/greg-finley/lichess-bot-min-opponent-moves/tree/main/MinOpponentMovesSetup) and [here](https://github.com/greg-finley/lichess-bot-min-opponent-moves/tree/main/AlphaBoticalSetup).

**Comment by MarkZH** [comment]
Does the freeze happen immediately when you start the second bot, or after a time? Can you post logs from when the freezes occur?

**Comment by greg-finley** [comment]
Yeah it's immediate. The screen just locks up and I can't get back into the vm with another ssh, so wasn't able to get any logs.

**Comment by greg-finley** [comment]
Just curious if you’ve ever tried something like this before? If it works for other people / other environments, that’s potentially useful info.

**Comment by greg-finley** [comment]
Ah probably too hard to stop the remote bots and move back to local. I can give up for now. 🙂

**Comment by greg-finley** [comment]
Closing the loop, if I switch away from shared core machines, it is possible to run two bots on one machine.
