### ISSUE TITLE
Add support for takeback requests

### ISSUE THREAD

**Issue by fathzer** [lichess-bot-devs/lichess-bot#934]
**The problem:**
Currently if we configure the bot account, in Lichess web site, to allow takeback offers, the opponent of the bot can request takeback. But he will never have any answer because the Bot doesn't listen for incoming events while thinking ([see @MarkZH comment on issue #60](https://github.com/lichess-bot-devs/lichess-bot/issues/60#issuecomment-2019503582))

**The solution I'd like:**
The bot should, at least, accept every takeback request it receives. We can also imagine allowing only a limited takeback count per game.

**Comment by MarkZH** [comment]
I've created a pull request to implement this. Let us know if it suits your purposes and if the limitations are acceptable.
