### ISSUE TITLE
Endpoint /api/stream/event is rate limited. Waiting 0:01:00 seconds until next request.

### ISSUE THREAD

**Issue by ezhang7423** [lichess-bot-devs/lichess-bot#943]
**Describe the bug**
When running this repository from scratch with no modifications, I am getting this error:

`<Response [429]> 429 {"error":"Please don't poll this endpoint, it is intended to be streamed. See https://lichess.org/api#tag/Board/operation/apiStreamEvent."}`

`Endpoint /api/stream/event is rate limited. Waiting 0:01:00 seconds until next request.`

**To Reproduce**
1. Run lichess-bot after following instructions in README.md: `python lichess-bot.py`
2. See error

**Expected behavior**
I expect that getting events should be able to succeed.

**Logs**

[old.log](https://github.com/lichess-bot-devs/lichess-bot/files/14958628/old.log)
[recent.log](https://github.com/lichess-bot-devs/lichess-bot/files/14958629/recent.log)

![image](https://github.com/lichess-bot-devs/lichess-bot/assets/54998055/8a0dacf1-927c-40a3-a1ef-ca16a3c39919)

**Desktop (please complete the following information):**
 - OS: linux
 - Python Version: 3.10
 - Terminal: bash

**Comment by ezhang7423** [comment]
Digging further, it seems like the code will call `/api/stream/event` several times in rapid succession:

```
https://lichess.org/api/stream/event None 15 True
[04/12/24 08:42:14] INFO     Next challenge will be created after 08:43:14 (0 challenges in last 24 hours)         matchmaking.py:292
<Response [200]> 200 
https://lichess.org/api/stream/event None 15 True
<Response [200]> 200 
https://lichess.org/api/stream/event None 15 True
<Response [200]> 200 
https://lichess.org/api/stream/event None 15 True
<Response [200]> 200 
https://lichess.org/api/stream/event None 15 True
<Response [200]> 200 
https://lichess.org/api/stream/event None 15 True
```

This happened within the course of a second...

**Comment by ezhang7423** [comment]
Another interesting note...this seems to happen because of a certain API token. When switching to a different API token, there is no issue...

**Comment by MarkZH** [comment]
What scopes are on the two API tokens? Go to the [API access tokens](https://lichess.org/account/oauth/token) page in your bot's preferences on lichess to see a list. Label the lists to indicate which one causes problems and which doesn't.

**Comment by ezhang7423** [comment]
Both API tokens have the correct scopes - the API token that is currently not working was working just a few days ago. If you're open to it, I can DM you privately the API token to debug with.

**Comment by MarkZH** [comment]
@ezhang7423 Sure, that will be useful. I'm `m.z.h` on the lichess discord server.

**Comment by MarkZH** [comment]
Please reopen if the problem persists and you can provide more details.
