### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by WilfriedDerHaarige** [lichess-bot-devs/lichess-bot#947]
Whenever i start a game for my Bot on lichess i get the Error Message:
[04/28/24 18:28:01] INFO     Backing off play_game(...) for 46.3s (OSError: [WinError 193] %1 is not a valid Win32 application)
   _common.py:105     
![Bild_2024-04-28_183240748](https://github.com/lichess-bot-devs/lichess-bot/assets/151431239/7d289cce-2777-4d5f-b0c4-3c8e86d7c2d9)
and my Bot doesnt make a move

**Comment by AttackingOrDefending** [comment]
Can you upload `lichess_bot_auto_logs/recent.log`, so we can look more into it?

**Comment by MarkZH** [comment]
Please reopen when you can provide more details about the problem.
