### ISSUE TITLE
Docker image is broken since 2024.5.3.2

### ISSUE THREAD

**Issue by fathzer** [lichess-bot-devs/lichess-bot#953]
**Describe the bug**
The docker run command `docker run -d -v /home/me/myEngine:/lichess-bot/config --name myBot lichessbotdevs/lichess-bot` that worked with 2024.5.3.1 results in the container to fail during startup with the following log content:
```
2024-05-06 18:28:23 /bin/sh: docker/copy_files.sh: Permission denied
```

**To Reproduce**
My configuration folder contains `config.yml` and `homemade.py`.

**Expected behavior**
The container should run as with previous releases.

**Logs**
See above.

**Desktop:**
 - OS: Windows 11 with Docker Desktop
 - Terminal: PowerShell

**Additional context**
As I wrote [here](https://github.com/lichess-bot-devs/lichess-bot/pull/936#issuecomment-2043038504). Having a pre-launch script that copies files in the container file system is not optimal. In my opinion, it is a step in the wrong direction. My advice is to revert the #951 PR and to develop an indirect access to `homemade.py` like I did for `extra_game_handlers.py`.

**Comment by fathzer** [comment]
Please remove the 2024.5.3.2 and 2024.5.3.2:alpine from your repositories, both are tagged with my name as a maintainer, but I didn't approve them.

**Comment by AttackingOrDefending** [comment]
Done.
