### ISSUE TITLE
how do i run the project

### ISSUE THREAD

**Issue by realBravo** [lichess-bot-devs/lichess-bot#968]
how do i run the project? 
which file do i run there is no main.py

**Comment by AttackingOrDefending** [comment]
You run `lichess-bot.py`. You can see the different options for running lichess-bot [here](https://github.com/lichess-bot-devs/lichess-bot/wiki/How-to-Run-lichess%E2%80%90bot). For general instructions to setup lichess-bot, you can look [here](https://github.com/lichess-bot-devs/lichess-bot/wiki).

**Comment by realBravo** [comment]
where is  config.yml

**Comment by realBravo** [comment]
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/josebravosango/code/lichess-bot.py': [Errno 2] No such file or directory

**Comment by realBravo** [comment]
im getting an error when trying to upgrade to bot account
